# Generated by Django 5.1.7 on 2025-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
